disabled_rules:
  - force_cast
  - void_return
excluded:
  - Submodules/
  - RxAlamofire/
attributes: true
closure_end_indentation: true
closure_spacing: true
conditional_returns_on_newline: true
discouraged_object_literal: true
discouraged_optional_boolean: true
empty_count: true
empty_string: true
explicit_enum_raw_value: true
explicit_top_level_acl: true
explicit_type_interface: true
fatal_error_message: true
file_header: true
file_length:
  warning: 800
  error: 1200
first_where: true
force_unwrapping: true
function_body_length:
  warning: 40
  error: 50
implicit_return: true
implicitly_unwrapped_optional: true
let_var_whitespace: true
line_length:
  warning: 150
  error: 160
literal_expression_end_indentation: true
multiline_arguments: true
multiline_parameters: true
operator_usage_whitespace: true
override_in_extension: true
private_action: true
private_outlet: true
required_enum_case: true
sorted_imports: true
strict_fileprivate: true
switch_case_on_newline: true
trailing_closure: true
type_body_length:
  warning: 500
  error: 1000
unneeded_parentheses_in_closure_argument: true
unused_optional_binding: true
vertical_parameter_alignment: true
vertical_parameter_alignment_on_call: true
yoda_condition: true
