# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

opt_out_usage

update_fastlane

default_platform(:ios)
platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Builds using the dev environment"
  lane :dev do
    sync_code_signing(type: "development", readonly: true)
    build_app(
      clean: true,
      export_method: "package",
      include_bitcode: false,
      include_symbols: true,
      scheme: "Blockchain (Dev)",
      workspace: "Blockchain.xcworkspace"
    )
    if is_ci?
      # Send Slack notification to #ios-ci channel
      # slack(message: "App successfully build!")
    end
  end
  desc "Deploys staging environment build to TestFlight"
  lane :staging do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Blockchain.xcodeproj"
    )
    build_app(
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      scheme: "Blockchain (Staging)",
      workspace: "Blockchain.xcworkspace"
    )
    # upload_to_testflight
  end
  desc "Runs all unit tests"
  lane :unit_tests do
    scan(
      workspace: "Blockchain.xcworkspace",
      scheme: "Blockchain (Staging)",
      devices: ["iPhone X"],
      clean: true
    )
  end
end
