#
#  Fastfile
#
#  For more information about the Fastfile, see:
#  You can find the documentation at https://docs.fastlane.tools
#
#  For a list of all available actions, check out
#  https://docs.fastlane.tools/actions
#

opt_out_usage

default_platform(:ios)
platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Builds using the production environment"
  lane :dev do
    # Global parameters are loaded from the Matchfile
    match(
      readonly: true,
      type: "appstore"
    )
    # Global parameters are loaded from the Gymfile
    # gym(
    #   configuration: "Release",
    #   export_method: "app-store",
    #   export_options: "./exportOptions.plist",
    #   scheme: "Blockchain"
    # )
    # upload_to_testflight
    # increment_build_number(
    #   build_number: app_store_build_number + 1,
    #   xcodeproj: "Blockchain.xcodeproj"
    # )
    # if is_ci?
    #   slack(message: "App was successfully uploaded to TestFlight!")
    # end
  end
  desc "Upload to TestFlight"
  lane :upload do
    sync_code_signing(type: "appstore", readonly: true)
    upload_to_testflight
  end
end
